name: Build go app and push to Azure

env:
  REDIS_HOST: mlsa3.redis.cache.windows.net:6380
  REDIS_PASSWORD: elf7mgl7Tp9NNVaZADQOfIvDOCdQHtvUOAzCaBFGll8=
  AZURE_SERVICEBUS_HOSTNAME: Endpoint=sb://mlsa3queues.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=oEbjFXH6o+hLzyBjxRhkXg9JpAzWwRCyeYmziWZdCAI=

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Copy static template files
      run: xcopy /i templates build\templates

    - name: Go get az dependencies
      run: |
        go get github.com/Azure/azure-sdk-for-go/sdk/azidentity
        go get github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus

    - name: Build
      run: go build -o build/go-app.exe -v

    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v2
      with:
        # Name of the Azure Web App
        app-name: mlsa3
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        package: build/
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}